# Generated by Django 5.2.6 on 2025-11-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Book title", max_length=200)),
                ("author", models.CharField(help_text="Book author", max_length=100)),
                (
                    "publication_year",
                    models.IntegerField(
                        blank=True, help_text="Year published", null=True
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        help_text="ISBN number",
                        max_length=13,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["title"],
            },
        ),
    ]
